openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development servers
  - url: https://task-api-vvf0.onrender.com
    description: Production server on render
tags:
  - name: Tasks
    description: Task-related endpoints
paths:
  /tasks:
    $ref: paths/tasks.yaml
  /tasks/{id}:
    get:
      summary: Get task by ID
      tags:
        - Tasks
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            minimum: 1
            example: 1
          required: true
          description: Numeric ID of the user to get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./components/schemas/Task.yaml
        '400':
          description: ID is not a number
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Validation Failed
                  details:
                    type: array
                    items: string
                    example:
                    - "ID must be a number"

        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Task not found
        